### ISSUE TITLE
Make it easier to understand the difference between "Users" and "Pulse Users"

### ISSUE THREAD

**Issue by edmorley** [mozilla-services/pulseguardian#38]
"Users" are login email addresses for individual people, "Pulse users" are sets of username+password credential pairs that can be owned by one or more "Users".

I think it might be less confusing to rename "Pulse Users" to "Pulse Credentials" or similar (at least in the UI).

**Comment by markrcote** [comment]
Hm. That's not bad... is "Pulse Accounts" better or worse, you think?

**Comment by edmorley** [comment]
I think "Users" and "Pulse Accounts" is slightly better than "Users" and "Pulse Users", though perhaps still a bit confusing? I guess for me pulseguardian roughly equals pulse, so the concept of there being separate users for both and thus why different users for both was lost on me (plus also the many to many mapping, but anyway).

**Comment by edmorley** [comment]
Eugh not well worded, but hopefully you get the gist :-)

**Comment by markrcote** [comment]
Huh okay I knew the naming was a bit confusing but never thought about Pulse being thought of as PulseGuardian; but that's likely because I was involved in Pulse a long time ago.

I'm going to post to the newsgroup about switching "Pulse Users" to "Pulse Credentials" to get a feel if others think it's better (or at least not worse).

I'll have to think about how deep the change should go... tradeoff between clarity through the app and overly invasive changes. :)

**Comment by edmorley** [comment]
Yeah makes sense.

How about "Pulse Guardian Users" (for the caption in the UI at least; otherwise "Users") and "RabbitMQ Accounts"?

**Comment by markrcote** [comment]
First part landed in #151.

**Comment by markrcote** [comment]
First part of the second part landed in #161. :)

**Comment by djmitche** [comment]
I think this is less confusing now that "users" are via auth0.
